/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cabelereiro.gui;

import ConexaoBD.Conexao;
import Cabelereiro.DAO.ClientesDAO;
import Cabelereiro.DTO.ClientesDTO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luizg
 */
public class TelaClientes extends javax.swing.JFrame {


/**
     * Creates new form Clientes
     */
    public TelaClientes() {
    initComponents();
    try {
        Connection conexao = new Conexao().getConnection(); // Obtendo conexão
        new ClientesDAO(conexao); // Passando a conexão para o DAO
        listarClientes(); // Chamando o método para listar os clientes
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao conectar ao banco: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHorarioDeAtendimento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        CadastrarButton = new javax.swing.JButton();
        AtualizarButton = new javax.swing.JButton();
        ExcluirButton = new javax.swing.JButton();
        CarregarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 51, 0));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 102, 204));

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 48)); // NOI18N
        jLabel1.setText("Clientes");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nome");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Horario de Atendimento");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("CPF");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Telefone");

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClientes.setModel(new DefaultTableModel(     new Object[][]{},      new String[]{"Nome", "CPF", "DataNascimento", "Telefone", "Email", "Sexo"} ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        CadastrarButton.setText("Cadastrar");
        CadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarButtonActionPerformed(evt);
            }
        });

        AtualizarButton.setText("Atualizar");
        AtualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarButtonActionPerformed(evt);
            }
        });

        ExcluirButton.setText("Excluir");
        ExcluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirButtonActionPerformed(evt);
            }
        });

        CarregarButton.setText("Carregar Campos");
        CarregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarregarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHorarioDeAtendimento, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addGap(390, 390, 390))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCpf)
                                    .addComponent(txtTelefone)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtNome)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CadastrarButton)
                                .addGap(18, 18, 18)
                                .addComponent(AtualizarButton)
                                .addGap(29, 29, 29)
                                .addComponent(ExcluirButton)
                                .addGap(18, 18, 18)
                                .addComponent(CarregarButton))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHorarioDeAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone)
                    .addComponent(jLabel6))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastrarButton)
                    .addComponent(AtualizarButton)
                    .addComponent(ExcluirButton)
                    .addComponent(CarregarButton))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarButtonActionPerformed
      try {
          atualizarClientes();
      } catch (SQLException ex) {
          Logger.getLogger(TelaClientes.class.getName()).log(Level.SEVERE, null, ex);
      }
        listarClientes();
        limparCamposClientes();
    }//GEN-LAST:event_AtualizarButtonActionPerformed

    private void ExcluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirButtonActionPerformed

        excluirClientes();
        listarClientes();
        limparCamposClientes();
    }//GEN-LAST:event_ExcluirButtonActionPerformed

    private void CarregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarregarButtonActionPerformed
        carregarCampos();
    }//GEN-LAST:event_CarregarButtonActionPerformed

    private void CadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarButtonActionPerformed
        cadastrarClientes();
    }//GEN-LAST:event_CadastrarButtonActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
          int selectedRow = tblClientes.getSelectedRow();
    System.out.println("📌 Linha clicada: " + selectedRow);

    }//GEN-LAST:event_tblClientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtualizarButton;
    private javax.swing.JButton CadastrarButton;
    private javax.swing.JButton CarregarButton;
    private javax.swing.JButton ExcluirButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtHorarioDeAtendimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
private void cadastrarClientes() {
    // Capturando os dados do textField
    String nome = txtNome.getText();
    String cpf = txtCpf.getText().trim();
    String telefone = txtTelefone.getText().trim();
    String horarioAtendimento = txtHorarioDeAtendimento.getText().trim();

    if (cpf.isEmpty() || telefone.isEmpty() || nome.isEmpty()) {
        JOptionPane.showMessageDialog(null, "❌ Preencha todos os campos obrigatórios!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Criando o objeto ClientesDTO
        ClientesDTO novoCliente = new ClientesDTO(nome, cpf, horarioAtendimento, telefone);
        
        System.out.println("Dados capturados do formulario: " + novoCliente.toString());

        // Query SQL para inserir o hóspede
        String query = "INSERT INTO clientes (nome, cpf, telefone, hararioAtendimento) VALUES (?, ?, ?, ?, ?, ?)";

        // Executa o comando SQL usando o método da classe Conexao
        boolean sucesso = Conexao.executarComandoSQL(query, nome, cpf, telefone, horarioAtendimento);

        if (sucesso) {
            JOptionPane.showMessageDialog(null, "Hóspede cadastrado com sucesso.");
            listarClientes(); // Atualiza a tabela
            limparCamposCliente();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar clientes.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao cadastrar clientes: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
}

private void atualizarClientes() throws SQLException {
    int selectedRow = tblClientes.getSelectedRow(); // 🔹 Obtém a linha selecionada
    System.out.println("📌 Tentando atualizar... Linha selecionada: " + selectedRow);

    if (selectedRow == -1) {  // Se nenhuma linha estiver selecionada, exibe erro
        JOptionPane.showMessageDialog(null, "❌ Nenhum cliente foi selecionado!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Obtém o CPF do cliente selecionado
    String cpfClienteSelecionado = (String) tblClientes.getValueAt(selectedRow, 1); // Coluna 1 = CPF
    System.out.println("📌 CPF do cliente selecionado: " + cpfClienteSelecionado);

    if (cpfClienteSelecionado.isEmpty()) {
        JOptionPane.showMessageDialog(null, "CPF do cliente inválido.", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Obtém os dados dos campos
    String nome = txtNome.getText();
    String cpf = txtCpf.getText();
    String telefone = txtTelefone.getText();
    String horarioAtendimento = txtHorarioDeAtendimento.getText();

    if (nome.isEmpty() || cpf.isEmpty() || telefone.isEmpty() || horarioAtendimento.isEmpty()) {
        JOptionPane.showMessageDialog(null, "❌ Preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // SQL para atualizar o cliente
    String query = "UPDATE clientes SET nome = ?, cpf = ?, telefone = ?, hararioAtendimento = ? WHERE cpf = ?";

    boolean sucesso = Conexao.executarComandoSQL(query, nome, cpf, telefone, horarioAtendimento, cpfClienteSelecionado);

    if (sucesso) {
        JOptionPane.showMessageDialog(null, "✅ Cliente atualizado com sucesso.");
        listarClientes();  // Atualiza a tabela
    } else {
        JOptionPane.showMessageDialog(null, "❌ Erro ao atualizar o cliente.", "Erro", JOptionPane.ERROR_MESSAGE);
    }
}

private void excluirCliente() {
    int selectedRow = tblClientes.getSelectedRow(); // Obtém a linha selecionada

    if (selectedRow == -1) {  // Verifica se um cliente foi selecionado
        JOptionPane.showMessageDialog(null, "Selecione um cliente para excluir.", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Obtém o CPF do hóspede selecionado
    String cpfClienteSelecionado = (String) tblClientes.getValueAt(selectedRow, 1); // Coluna 1 = CPF
    System.out.println("CPF do cliente a excluir: " + cpfClienteSelecionado);  // 🔥 Debug

    String query = "DELETE FROM clientes WHERE cpf = ?";

    // Chama o método do ConexaoDAO para executar a exclusão
    boolean sucesso = Conexao.executarComandoSQL(query, cpfClienteSelecionado);

    if (sucesso) {
        JOptionPane.showMessageDialog(null, "Cliente excluído com sucesso.");
        listarClientes();  // Atualiza a lista de clientes
    } else {
        JOptionPane.showMessageDialog(null, "Erro ao excluir o cliente.", "Erro", JOptionPane.ERROR_MESSAGE);
    }
}

private void listarClientes() {
    try {
        String query = "SELECT * FROM cliente";
        
        // Usando a classe Conexao para obter a conexão
        try (Connection conn = new Conexao().getConnection(); // Obtém a conexão
             PreparedStatement pst = conn.prepareStatement(query);
             ResultSet rs = pst.executeQuery()) {

            DefaultTableModel model = (DefaultTableModel) tblClientes.getModel();
            model.setNumRows(0); // Limpa a tabela antes de adicionar novos dados

            while (rs.next()) {
                Object[] rowData = {
                    rs.getString("nome"),
                    rs.getString("cpf"),
                    rs.getString("horarioAtendimento"),
                    rs.getString("telefone"),
                };
                model.addRow(rowData);
            }
            tblClientes.repaint(); // Atualiza a tabela
            tblClientes.revalidate();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao carregar os clientes: " + e.getMessage());
    }
}

private void carregarCampos() {
    int selectedRow = tblClientes.getSelectedRow();
    if (selectedRow != -1) {
        txtNome.setText(tblClientes.getValueAt(selectedRow, 0).toString());
        txtCpf.setText(tblClientes.getValueAt(selectedRow, 1).toString());
        txtHorarioDeAtendimento.setText(tblClientes.getValueAt(selectedRow, 2).toString());
        txtTelefone.setText(tblClientes.getValueAt(selectedRow, 3).toString());
        
        
    } else {
        System.out.println("Nenhum cliente selecionado.");
    }
}

private void limparCamposCliente() {
    txtNome.setText(null);
    txtCpf.setText(null);
    txtHorarioDeAtendimento.setText(null);
    txtTelefone.setText(null);
    txtNome.requestFocus();  
} 

    private void limparCamposClientes() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void excluirClientes() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}